# Generated by Django 4.1 on 2022-12-02 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='deleted date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=255, verbose_name='task.title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='deleted date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('node_level', models.PositiveSmallIntegerField(default=0, verbose_name='node_level')),
                ('is_leaf', models.BooleanField(default=False, verbose_name='is_leaf')),
                ('code', models.CharField(max_length=50, verbose_name='skill_code')),
                ('name', models.CharField(max_length=255, verbose_name='skill_name')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evaluation_competency', to='competency.competency', verbose_name='competency')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competency.skillevaluation', verbose_name='skill_parent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='deleted date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('node_level', models.PositiveSmallIntegerField(default=0, verbose_name='node_level')),
                ('is_leaf', models.BooleanField(default=False, verbose_name='is_leaf')),
                ('code', models.CharField(max_length=50, verbose_name='task_code')),
                ('name', models.CharField(max_length=255, verbose_name='task_name')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_evaluation_competency', to='competency.competency', verbose_name='competency')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competency.taskevaluation', verbose_name='task_parent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='deleted date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('skill_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_skill_skill_evaluation', to='competency.skillevaluation', verbose_name='skill_evaluation')),
                ('task_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_skill_task_evaluation', to='competency.taskevaluation', verbose_name='task_evaluation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='deleted date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('node_level', models.PositiveSmallIntegerField(default=0, verbose_name='node_level')),
                ('is_leaf', models.BooleanField(default=False, verbose_name='is_leaf')),
                ('code', models.CharField(max_length=50, verbose_name='task_item_code')),
                ('name', models.CharField(max_length=255, verbose_name='task_item_name')),
                ('description', models.CharField(max_length=255, verbose_name='task_item_name')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_profile_competency', to='competency.competency', verbose_name='competency')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competency.taskprofile', verbose_name='task_profile_parent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskFulltext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='deleted date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('contents', models.TextField(verbose_name='task_fulltext_contents')),
                ('task_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_fulltext_task_evaluation', to='competency.taskevaluation', verbose_name='task_evaluation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskEvaluationTaskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='deleted date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('weight', models.PositiveSmallIntegerField(default=0, verbose_name='task_profile_relation_weight')),
                ('task_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_evaluation_profile_task_evaluation', to='competency.taskevaluation', verbose_name='task_evaluation')),
                ('task_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_evaluation_profile_task_profile', to='competency.taskprofile', verbose_name='task_evaluation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskEvaluationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='deleted date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('node_level', models.PositiveSmallIntegerField(default=0, verbose_name='node_level')),
                ('is_leaf', models.BooleanField(default=False, verbose_name='is_leaf')),
                ('code', models.CharField(max_length=50, verbose_name='task_item_code')),
                ('name', models.CharField(max_length=255, verbose_name='task_item_name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competency.taskevaluationitem', verbose_name='task_item_parent')),
                ('task_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_evaluation_item_task_evaluation', to='competency.taskevaluation', verbose_name='task_evaluation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillEvaluationKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='deleted date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('node_level', models.PositiveSmallIntegerField(default=0, verbose_name='node_level')),
                ('is_leaf', models.BooleanField(default=False, verbose_name='is_leaf')),
                ('code', models.CharField(max_length=50, verbose_name='skill_knowledge_code')),
                ('name', models.CharField(max_length=255, verbose_name='skill_knowledge_name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competency.skillevaluationknowledge', verbose_name='skill_knowledge_parent')),
                ('skill_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evaluation_knowledge_skill_evaluation', to='competency.skillevaluation', verbose_name='skill_evaluation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
