# Generated by Django 4.1 on 2022-12-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='deleted date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('word', models.CharField(db_index=True, max_length=100, verbose_name='task_search_word')),
                ('synonym', models.CharField(db_index=True, max_length=100, verbose_name='task_search_word')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
